
# encoding: utf-8

# *** GENERATED BY `setup.py antlr`, DO NOT EDIT BY HAND ***
#
# Generated from ../LaTeX.g4, derived from latex2sympy
#     latex2sympy is licensed under the MIT license
#     https://github.com/augustt198/latex2sympy/blob/master/LICENSE.txt
#
# Generated with antlr4
#    antlr4 is licensed under the BSD-3-Clause License
#    https://github.com/antlr/antlr4/blob/master/LICENSE.txt

# *** GENERATED BY `setup.py antlr`, DO NOT EDIT BY HAND ***
#
# Generated from ../LaTeX.g4, derived from latex2sympy
#     latex2sympy is licensed under the MIT license
#     https://github.com/augustt198/latex2sympy/blob/master/LICENSE.txt
#
# Generated with antlr4
#    antlr4 is licensed under the BSD-3-Clause License
#    https://github.com/antlr/antlr4/blob/master/LICENSE.txt
from __future__ import print_function
from antlr4 import *
from io import StringIO
import sys



def serializedATN():
    with StringIO() as buf:
        buf.write(u"\3\u608b\ua72a\u8133\ub9ed\u417c\u3be7\u7786\u5964\2")
        buf.write(u"M\u02c6\b\1\4\2\t\2\4\3\t\3\4\4\t\4\4\5\t\5\4\6\t\6\4")
        buf.write(u"\7\t\7\4\b\t\b\4\t\t\t\4\n\t\n\4\13\t\13\4\f\t\f\4\r")
        buf.write(u"\t\r\4\16\t\16\4\17\t\17\4\20\t\20\4\21\t\21\4\22\t\22")
        buf.write(u"\4\23\t\23\4\24\t\24\4\25\t\25\4\26\t\26\4\27\t\27\4")
        buf.write(u"\30\t\30\4\31\t\31\4\32\t\32\4\33\t\33\4\34\t\34\4\35")
        buf.write(u"\t\35\4\36\t\36\4\37\t\37\4 \t \4!\t!\4\"\t\"\4#\t#\4")
        buf.write(u"$\t$\4%\t%\4&\t&\4\'\t\'\4(\t(\4)\t)\4*\t*\4+\t+\4,\t")
        buf.write(u",\4-\t-\4.\t.\4/\t/\4\60\t\60\4\61\t\61\4\62\t\62\4\63")
        buf.write(u"\t\63\4\64\t\64\4\65\t\65\4\66\t\66\4\67\t\67\48\t8\4")
        buf.write(u"9\t9\4:\t:\4;\t;\4<\t<\4=\t=\4>\t>\4?\t?\4@\t@\4A\tA")
        buf.write(u"\4B\tB\4C\tC\4D\tD\4E\tE\4F\tF\4G\tG\4H\tH\4I\tI\4J\t")
        buf.write(u"J\4K\tK\4L\tL\4M\tM\4N\tN\3\2\3\2\3\3\6\3\u00a1\n\3\r")
        buf.write(u"\3\16\3\u00a2\3\3\3\3\3\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4")
        buf.write(u"\3\4\3\4\3\4\3\4\5\4\u00b3\n\4\3\4\3\4\3\5\3\5\3\5\3")
        buf.write(u"\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\5\5\u00c2\n\5\3\5\3\5")
        buf.write(u"\3\6\3\6\3\6\3\6\3\6\3\6\3\6\3\6\3\6\3\6\3\6\3\6\3\6")
        buf.write(u"\5\6\u00d3\n\6\3\6\3\6\3\7\3\7\3\7\3\7\3\7\3\7\3\7\3")
        buf.write(u"\7\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\t\3\t\3\t\3")
        buf.write(u"\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\5\t\u00f7")
        buf.write(u"\n\t\3\t\3\t\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n")
        buf.write(u"\3\n\3\n\3\n\3\n\3\n\3\13\3\13\3\13\3\13\3\13\3\13\3")
        buf.write(u"\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13")
        buf.write(u"\3\f\3\f\3\r\3\r\3\16\3\16\3\17\3\17\3\20\3\20\3\21\3")
        buf.write(u"\21\3\22\3\22\3\23\3\23\3\24\3\24\3\24\3\25\3\25\3\25")
        buf.write(u"\3\26\3\26\3\27\3\27\3\30\3\30\3\30\3\30\3\30\3\30\3")
        buf.write(u"\30\3\30\3\31\3\31\3\31\3\31\3\31\3\31\3\31\3\31\3\31")
        buf.write(u"\3\32\3\32\3\32\3\32\3\32\3\32\3\32\3\32\3\32\3\33\3")
        buf.write(u"\33\3\33\3\33\3\33\3\33\3\33\3\33\3\33\3\33\3\34\3\34")
        buf.write(u"\3\35\3\35\3\35\3\35\3\35\3\36\3\36\3\36\3\36\3\36\3")
        buf.write(u"\36\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3\36")
        buf.write(u"\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3")
        buf.write(u"\36\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3\36")
        buf.write(u"\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3")
        buf.write(u"\36\3\36\3\36\3\36\3\36\3\36\3\36\3\36\5\36\u0197\n\36")
        buf.write(u"\3\37\3\37\3\37\3\37\3\37\3 \3 \3 \3 \3 \3!\3!\3!\3!")
        buf.write(u"\3!\3!\3\"\3\"\3\"\3\"\3\"\3#\3#\3#\3#\3#\3$\3$\3$\3")
        buf.write(u"$\3%\3%\3%\3%\3%\3&\3&\3&\3&\3&\3\'\3\'\3\'\3\'\3\'\3")
        buf.write(u"(\3(\3(\3(\3(\3)\3)\3)\3)\3)\3*\3*\3*\3*\3*\3+\3+\3+")
        buf.write(u"\3+\3+\3+\3+\3+\3,\3,\3,\3,\3,\3,\3,\3,\3-\3-\3-\3-\3")
        buf.write(u"-\3-\3-\3-\3.\3.\3.\3.\3.\3.\3.\3.\3/\3/\3/\3/\3/\3/")
        buf.write(u"\3/\3/\3\60\3\60\3\60\3\60\3\60\3\60\3\60\3\60\3\61\3")
        buf.write(u"\61\3\61\3\61\3\61\3\61\3\62\3\62\3\62\3\62\3\62\3\62")
        buf.write(u"\3\63\3\63\3\63\3\63\3\63\3\63\3\64\3\64\3\64\3\64\3")
        buf.write(u"\64\3\64\3\64\3\64\3\65\3\65\3\65\3\65\3\65\3\65\3\65")
        buf.write(u"\3\65\3\66\3\66\3\66\3\66\3\66\3\66\3\66\3\66\3\67\3")
        buf.write(u"\67\3\67\3\67\3\67\3\67\38\38\38\38\38\38\38\39\39\3")
        buf.write(u"9\39\39\39\3:\3:\3:\3:\3:\3;\3;\3;\3;\3;\3;\3<\3<\3<")
        buf.write(u"\3<\3<\3<\3<\3=\3=\3=\3=\3=\3=\3=\3=\3>\3>\3>\3>\3>\3")
        buf.write(u">\3>\3>\3?\3?\3?\3?\3?\3?\3?\3?\3@\3@\3A\3A\3B\3B\3C")
        buf.write(u"\3C\3D\3D\7D\u0276\nD\fD\16D\u0279\13D\3D\3D\3D\6D\u027e")
        buf.write(u"\nD\rD\16D\u027f\5D\u0282\nD\3E\3E\3F\3F\3G\6G\u0289")
        buf.write(u"\nG\rG\16G\u028a\3G\3G\3G\3G\3G\7G\u0292\nG\fG\16G\u0295")
        buf.write(u"\13G\3G\7G\u0298\nG\fG\16G\u029b\13G\3G\3G\3G\3G\3G\7")
        buf.write(u"G\u02a2\nG\fG\16G\u02a5\13G\3G\3G\6G\u02a9\nG\rG\16G")
        buf.write(u"\u02aa\5G\u02ad\nG\3H\3H\3I\3I\3J\3J\3J\3J\3J\3K\3K\3")
        buf.write(u"L\3L\3L\3L\3L\3M\3M\3N\3N\6N\u02c3\nN\rN\16N\u02c4\3")
        buf.write(u"\u0277\2O\3\3\5\4\7\5\t\6\13\7\r\b\17\t\21\n\23\13\25")
        buf.write(u"\f\27\r\31\16\33\17\35\20\37\21!\22#\23%\24\'\25)\26")
        buf.write(u"+\27-\30/\31\61\32\63\33\65\34\67\359\36;\37= ?!A\"C")
        buf.write(u"#E$G%I&K\'M(O)Q*S+U,W-Y.[/]\60_\61a\62c\63e\64g\65i\66")
        buf.write(u"k\67m8o9q:s;u<w=y>{?}@\177A\u0081B\u0083C\u0085\2\u0087")
        buf.write(u"D\u0089E\u008b\2\u008dF\u008fG\u0091H\u0093I\u0095J\u0097")
        buf.write(u"K\u0099L\u009bM\3\2\5\5\2\13\f\17\17\"\"\4\2C\\c|\3\2")
        buf.write(u"\62;\2\u02d6\2\3\3\2\2\2\2\5\3\2\2\2\2\7\3\2\2\2\2\t")
        buf.write(u"\3\2\2\2\2\13\3\2\2\2\2\r\3\2\2\2\2\17\3\2\2\2\2\21\3")
        buf.write(u"\2\2\2\2\23\3\2\2\2\2\25\3\2\2\2\2\27\3\2\2\2\2\31\3")
        buf.write(u"\2\2\2\2\33\3\2\2\2\2\35\3\2\2\2\2\37\3\2\2\2\2!\3\2")
        buf.write(u"\2\2\2#\3\2\2\2\2%\3\2\2\2\2\'\3\2\2\2\2)\3\2\2\2\2+")
        buf.write(u"\3\2\2\2\2-\3\2\2\2\2/\3\2\2\2\2\61\3\2\2\2\2\63\3\2")
        buf.write(u"\2\2\2\65\3\2\2\2\2\67\3\2\2\2\29\3\2\2\2\2;\3\2\2\2")
        buf.write(u"\2=\3\2\2\2\2?\3\2\2\2\2A\3\2\2\2\2C\3\2\2\2\2E\3\2\2")
        buf.write(u"\2\2G\3\2\2\2\2I\3\2\2\2\2K\3\2\2\2\2M\3\2\2\2\2O\3\2")
        buf.write(u"\2\2\2Q\3\2\2\2\2S\3\2\2\2\2U\3\2\2\2\2W\3\2\2\2\2Y\3")
        buf.write(u"\2\2\2\2[\3\2\2\2\2]\3\2\2\2\2_\3\2\2\2\2a\3\2\2\2\2")
        buf.write(u"c\3\2\2\2\2e\3\2\2\2\2g\3\2\2\2\2i\3\2\2\2\2k\3\2\2\2")
        buf.write(u"\2m\3\2\2\2\2o\3\2\2\2\2q\3\2\2\2\2s\3\2\2\2\2u\3\2\2")
        buf.write(u"\2\2w\3\2\2\2\2y\3\2\2\2\2{\3\2\2\2\2}\3\2\2\2\2\177")
        buf.write(u"\3\2\2\2\2\u0081\3\2\2\2\2\u0083\3\2\2\2\2\u0087\3\2")
        buf.write(u"\2\2\2\u0089\3\2\2\2\2\u008d\3\2\2\2\2\u008f\3\2\2\2")
        buf.write(u"\2\u0091\3\2\2\2\2\u0093\3\2\2\2\2\u0095\3\2\2\2\2\u0097")
        buf.write(u"\3\2\2\2\2\u0099\3\2\2\2\2\u009b\3\2\2\2\3\u009d\3\2")
        buf.write(u"\2\2\5\u00a0\3\2\2\2\7\u00b2\3\2\2\2\t\u00c1\3\2\2\2")
        buf.write(u"\13\u00d2\3\2\2\2\r\u00d6\3\2\2\2\17\u00de\3\2\2\2\21")
        buf.write(u"\u00f6\3\2\2\2\23\u00fa\3\2\2\2\25\u0109\3\2\2\2\27\u011a")
        buf.write(u"\3\2\2\2\31\u011c\3\2\2\2\33\u011e\3\2\2\2\35\u0120\3")
        buf.write(u"\2\2\2\37\u0122\3\2\2\2!\u0124\3\2\2\2#\u0126\3\2\2\2")
        buf.write(u"%\u0128\3\2\2\2\'\u012a\3\2\2\2)\u012d\3\2\2\2+\u0130")
        buf.write(u"\3\2\2\2-\u0132\3\2\2\2/\u0134\3\2\2\2\61\u013c\3\2\2")
        buf.write(u"\2\63\u0145\3\2\2\2\65\u014e\3\2\2\2\67\u0158\3\2\2\2")
        buf.write(u"9\u015a\3\2\2\2;\u0196\3\2\2\2=\u0198\3\2\2\2?\u019d")
        buf.write(u"\3\2\2\2A\u01a2\3\2\2\2C\u01a8\3\2\2\2E\u01ad\3\2\2\2")
        buf.write(u"G\u01b2\3\2\2\2I\u01b6\3\2\2\2K\u01bb\3\2\2\2M\u01c0")
        buf.write(u"\3\2\2\2O\u01c5\3\2\2\2Q\u01ca\3\2\2\2S\u01cf\3\2\2\2")
        buf.write(u"U\u01d4\3\2\2\2W\u01dc\3\2\2\2Y\u01e4\3\2\2\2[\u01ec")
        buf.write(u"\3\2\2\2]\u01f4\3\2\2\2_\u01fc\3\2\2\2a\u0204\3\2\2\2")
        buf.write(u"c\u020a\3\2\2\2e\u0210\3\2\2\2g\u0216\3\2\2\2i\u021e")
        buf.write(u"\3\2\2\2k\u0226\3\2\2\2m\u022e\3\2\2\2o\u0234\3\2\2\2")
        buf.write(u"q\u023b\3\2\2\2s\u0241\3\2\2\2u\u0246\3\2\2\2w\u024c")
        buf.write(u"\3\2\2\2y\u0253\3\2\2\2{\u025b\3\2\2\2}\u0263\3\2\2\2")
        buf.write(u"\177\u026b\3\2\2\2\u0081\u026d\3\2\2\2\u0083\u026f\3")
        buf.write(u"\2\2\2\u0085\u0271\3\2\2\2\u0087\u0273\3\2\2\2\u0089")
        buf.write(u"\u0283\3\2\2\2\u008b\u0285\3\2\2\2\u008d\u02ac\3\2\2")
        buf.write(u"\2\u008f\u02ae\3\2\2\2\u0091\u02b0\3\2\2\2\u0093\u02b2")
        buf.write(u"\3\2\2\2\u0095\u02b7\3\2\2\2\u0097\u02b9\3\2\2\2\u0099")
        buf.write(u"\u02be\3\2\2\2\u009b\u02c0\3\2\2\2\u009d\u009e\7.\2\2")
        buf.write(u"\u009e\4\3\2\2\2\u009f\u00a1\t\2\2\2\u00a0\u009f\3\2")
        buf.write(u"\2\2\u00a1\u00a2\3\2\2\2\u00a2\u00a0\3\2\2\2\u00a2\u00a3")
        buf.write(u"\3\2\2\2\u00a3\u00a4\3\2\2\2\u00a4\u00a5\b\3\2\2\u00a5")
        buf.write(u"\6\3\2\2\2\u00a6\u00a7\7^\2\2\u00a7\u00b3\7.\2\2\u00a8")
        buf.write(u"\u00a9\7^\2\2\u00a9\u00aa\7v\2\2\u00aa\u00ab\7j\2\2\u00ab")
        buf.write(u"\u00ac\7k\2\2\u00ac\u00ad\7p\2\2\u00ad\u00ae\7u\2\2\u00ae")
        buf.write(u"\u00af\7r\2\2\u00af\u00b0\7c\2\2\u00b0\u00b1\7e\2\2\u00b1")
        buf.write(u"\u00b3\7g\2\2\u00b2\u00a6\3\2\2\2\u00b2\u00a8\3\2\2\2")
        buf.write(u"\u00b3\u00b4\3\2\2\2\u00b4\u00b5\b\4\2\2\u00b5\b\3\2")
        buf.write(u"\2\2\u00b6\u00b7\7^\2\2\u00b7\u00c2\7<\2\2\u00b8\u00b9")
        buf.write(u"\7^\2\2\u00b9\u00ba\7o\2\2\u00ba\u00bb\7g\2\2\u00bb\u00bc")
        buf.write(u"\7f\2\2\u00bc\u00bd\7u\2\2\u00bd\u00be\7r\2\2\u00be\u00bf")
        buf.write(u"\7c\2\2\u00bf\u00c0\7e\2\2\u00c0\u00c2\7g\2\2\u00c1\u00b6")
        buf.write(u"\3\2\2\2\u00c1\u00b8\3\2\2\2\u00c2\u00c3\3\2\2\2\u00c3")
        buf.write(u"\u00c4\b\5\2\2\u00c4\n\3\2\2\2\u00c5\u00c6\7^\2\2\u00c6")
        buf.write(u"\u00d3\7=\2\2\u00c7\u00c8\7^\2\2\u00c8\u00c9\7v\2\2\u00c9")
        buf.write(u"\u00ca\7j\2\2\u00ca\u00cb\7k\2\2\u00cb\u00cc\7e\2\2\u00cc")
        buf.write(u"\u00cd\7m\2\2\u00cd\u00ce\7u\2\2\u00ce\u00cf\7r\2\2\u00cf")
        buf.write(u"\u00d0\7c\2\2\u00d0\u00d1\7e\2\2\u00d1\u00d3\7g\2\2\u00d2")
        buf.write(u"\u00c5\3\2\2\2\u00d2\u00c7\3\2\2\2\u00d3\u00d4\3\2\2")
        buf.write(u"\2\u00d4\u00d5\b\6\2\2\u00d5\f\3\2\2\2\u00d6\u00d7\7")
        buf.write(u"^\2\2\u00d7\u00d8\7s\2\2\u00d8\u00d9\7w\2\2\u00d9\u00da")
        buf.write(u"\7c\2\2\u00da\u00db\7f\2\2\u00db\u00dc\3\2\2\2\u00dc")
        buf.write(u"\u00dd\b\7\2\2\u00dd\16\3\2\2\2\u00de\u00df\7^\2\2\u00df")
        buf.write(u"\u00e0\7s\2\2\u00e0\u00e1\7s\2\2\u00e1\u00e2\7w\2\2\u00e2")
        buf.write(u"\u00e3\7c\2\2\u00e3\u00e4\7f\2\2\u00e4\u00e5\3\2\2\2")
        buf.write(u"\u00e5\u00e6\b\b\2\2\u00e6\20\3\2\2\2\u00e7\u00e8\7^")
        buf.write(u"\2\2\u00e8\u00f7\7#\2\2\u00e9\u00ea\7^\2\2\u00ea\u00eb")
        buf.write(u"\7p\2\2\u00eb\u00ec\7g\2\2\u00ec\u00ed\7i\2\2\u00ed\u00ee")
        buf.write(u"\7v\2\2\u00ee\u00ef\7j\2\2\u00ef\u00f0\7k\2\2\u00f0\u00f1")
        buf.write(u"\7p\2\2\u00f1\u00f2\7u\2\2\u00f2\u00f3\7r\2\2\u00f3\u00f4")
        buf.write(u"\7c\2\2\u00f4\u00f5\7e\2\2\u00f5\u00f7\7g\2\2\u00f6\u00e7")
        buf.write(u"\3\2\2\2\u00f6\u00e9\3\2\2\2\u00f7\u00f8\3\2\2\2\u00f8")
        buf.write(u"\u00f9\b\t\2\2\u00f9\22\3\2\2\2\u00fa\u00fb\7^\2\2\u00fb")
        buf.write(u"\u00fc\7p\2\2\u00fc\u00fd\7g\2\2\u00fd\u00fe\7i\2\2\u00fe")
        buf.write(u"\u00ff\7o\2\2\u00ff\u0100\7g\2\2\u0100\u0101\7f\2\2\u0101")
        buf.write(u"\u0102\7u\2\2\u0102\u0103\7r\2\2\u0103\u0104\7c\2\2\u0104")
        buf.write(u"\u0105\7e\2\2\u0105\u0106\7g\2\2\u0106\u0107\3\2\2\2")
        buf.write(u"\u0107\u0108\b\n\2\2\u0108\24\3\2\2\2\u0109\u010a\7^")
        buf.write(u"\2\2\u010a\u010b\7p\2\2\u010b\u010c\7g\2\2\u010c\u010d")
        buf.write(u"\7i\2\2\u010d\u010e\7v\2\2\u010e\u010f\7j\2\2\u010f\u0110")
        buf.write(u"\7k\2\2\u0110\u0111\7e\2\2\u0111\u0112\7m\2\2\u0112\u0113")
        buf.write(u"\7u\2\2\u0113\u0114\7r\2\2\u0114\u0115\7c\2\2\u0115\u0116")
        buf.write(u"\7e\2\2\u0116\u0117\7g\2\2\u0117\u0118\3\2\2\2\u0118")
        buf.write(u"\u0119\b\13\2\2\u0119\26\3\2\2\2\u011a\u011b\7-\2\2\u011b")
        buf.write(u"\30\3\2\2\2\u011c\u011d\7/\2\2\u011d\32\3\2\2\2\u011e")
        buf.write(u"\u011f\7,\2\2\u011f\34\3\2\2\2\u0120\u0121\7\61\2\2\u0121")
        buf.write(u"\36\3\2\2\2\u0122\u0123\7*\2\2\u0123 \3\2\2\2\u0124\u0125")
        buf.write(u"\7+\2\2\u0125\"\3\2\2\2\u0126\u0127\7}\2\2\u0127$\3\2")
        buf.write(u"\2\2\u0128\u0129\7\177\2\2\u0129&\3\2\2\2\u012a\u012b")
        buf.write(u"\7^\2\2\u012b\u012c\7}\2\2\u012c(\3\2\2\2\u012d\u012e")
        buf.write(u"\7^\2\2\u012e\u012f\7\177\2\2\u012f*\3\2\2\2\u0130\u0131")
        buf.write(u"\7]\2\2\u0131,\3\2\2\2\u0132\u0133\7_\2\2\u0133.\3\2")
        buf.write(u"\2\2\u0134\u0135\7^\2\2\u0135\u0136\7n\2\2\u0136\u0137")
        buf.write(u"\7g\2\2\u0137\u0138\7h\2\2\u0138\u0139\7v\2\2\u0139\u013a")
        buf.write(u"\3\2\2\2\u013a\u013b\b\30\2\2\u013b\60\3\2\2\2\u013c")
        buf.write(u"\u013d\7^\2\2\u013d\u013e\7t\2\2\u013e\u013f\7k\2\2\u013f")
        buf.write(u"\u0140\7i\2\2\u0140\u0141\7j\2\2\u0141\u0142\7v\2\2\u0142")
        buf.write(u"\u0143\3\2\2\2\u0143\u0144\b\31\2\2\u0144\62\3\2\2\2")
        buf.write(u"\u0145\u0146\7^\2\2\u0146\u0147\7o\2\2\u0147\u0148\7")
        buf.write(u"n\2\2\u0148\u0149\7g\2\2\u0149\u014a\7h\2\2\u014a\u014b")
        buf.write(u"\7v\2\2\u014b\u014c\3\2\2\2\u014c\u014d\b\32\2\2\u014d")
        buf.write(u"\64\3\2\2\2\u014e\u014f\7^\2\2\u014f\u0150\7o\2\2\u0150")
        buf.write(u"\u0151\7t\2\2\u0151\u0152\7k\2\2\u0152\u0153\7i\2\2\u0153")
        buf.write(u"\u0154\7j\2\2\u0154\u0155\7v\2\2\u0155\u0156\3\2\2\2")
        buf.write(u"\u0156\u0157\b\33\2\2\u0157\66\3\2\2\2\u0158\u0159\7")
        buf.write(u"~\2\2\u01598\3\2\2\2\u015a\u015b\7^\2\2\u015b\u015c\7")
        buf.write(u"n\2\2\u015c\u015d\7k\2\2\u015d\u015e\7o\2\2\u015e:\3")
        buf.write(u"\2\2\2\u015f\u0160\7^\2\2\u0160\u0161\7v\2\2\u0161\u0197")
        buf.write(u"\7q\2\2\u0162\u0163\7^\2\2\u0163\u0164\7t\2\2\u0164\u0165")
        buf.write(u"\7k\2\2\u0165\u0166\7i\2\2\u0166\u0167\7j\2\2\u0167\u0168")
        buf.write(u"\7v\2\2\u0168\u0169\7c\2\2\u0169\u016a\7t\2\2\u016a\u016b")
        buf.write(u"\7t\2\2\u016b\u016c\7q\2\2\u016c\u0197\7y\2\2\u016d\u016e")
        buf.write(u"\7^\2\2\u016e\u016f\7T\2\2\u016f\u0170\7k\2\2\u0170\u0171")
        buf.write(u"\7i\2\2\u0171\u0172\7j\2\2\u0172\u0173\7v\2\2\u0173\u0174")
        buf.write(u"\7c\2\2\u0174\u0175\7t\2\2\u0175\u0176\7t\2\2\u0176\u0177")
        buf.write(u"\7q\2\2\u0177\u0197\7y\2\2\u0178\u0179\7^\2\2\u0179\u017a")
        buf.write(u"\7n\2\2\u017a\u017b\7q\2\2\u017b\u017c\7p\2\2\u017c\u017d")
        buf.write(u"\7i\2\2\u017d\u017e\7t\2\2\u017e\u017f\7k\2\2\u017f\u0180")
        buf.write(u"\7i\2\2\u0180\u0181\7j\2\2\u0181\u0182\7v\2\2\u0182\u0183")
        buf.write(u"\7c\2\2\u0183\u0184\7t\2\2\u0184\u0185\7t\2\2\u0185\u0186")
        buf.write(u"\7q\2\2\u0186\u0197\7y\2\2\u0187\u0188\7^\2\2\u0188\u0189")
        buf.write(u"\7N\2\2\u0189\u018a\7q\2\2\u018a\u018b\7p\2\2\u018b\u018c")
        buf.write(u"\7i\2\2\u018c\u018d\7t\2\2\u018d\u018e\7k\2\2\u018e\u018f")
        buf.write(u"\7i\2\2\u018f\u0190\7j\2\2\u0190\u0191\7v\2\2\u0191\u0192")
        buf.write(u"\7c\2\2\u0192\u0193\7t\2\2\u0193\u0194\7t\2\2\u0194\u0195")
        buf.write(u"\7q\2\2\u0195\u0197\7y\2\2\u0196\u015f\3\2\2\2\u0196")
        buf.write(u"\u0162\3\2\2\2\u0196\u016d\3\2\2\2\u0196\u0178\3\2\2")
        buf.write(u"\2\u0196\u0187\3\2\2\2\u0197<\3\2\2\2\u0198\u0199\7^")
        buf.write(u"\2\2\u0199\u019a\7k\2\2\u019a\u019b\7p\2\2\u019b\u019c")
        buf.write(u"\7v\2\2\u019c>\3\2\2\2\u019d\u019e\7^\2\2\u019e\u019f")
        buf.write(u"\7u\2\2\u019f\u01a0\7w\2\2\u01a0\u01a1\7o\2\2\u01a1@")
        buf.write(u"\3\2\2\2\u01a2\u01a3\7^\2\2\u01a3\u01a4\7r\2\2\u01a4")
        buf.write(u"\u01a5\7t\2\2\u01a5\u01a6\7q\2\2\u01a6\u01a7\7f\2\2\u01a7")
        buf.write(u"B\3\2\2\2\u01a8\u01a9\7^\2\2\u01a9\u01aa\7g\2\2\u01aa")
        buf.write(u"\u01ab\7z\2\2\u01ab\u01ac\7r\2\2\u01acD\3\2\2\2\u01ad")
        buf.write(u"\u01ae\7^\2\2\u01ae\u01af\7n\2\2\u01af\u01b0\7q\2\2\u01b0")
        buf.write(u"\u01b1\7i\2\2\u01b1F\3\2\2\2\u01b2\u01b3\7^\2\2\u01b3")
        buf.write(u"\u01b4\7n\2\2\u01b4\u01b5\7p\2\2\u01b5H\3\2\2\2\u01b6")
        buf.write(u"\u01b7\7^\2\2\u01b7\u01b8\7u\2\2\u01b8\u01b9\7k\2\2\u01b9")
        buf.write(u"\u01ba\7p\2\2\u01baJ\3\2\2\2\u01bb\u01bc\7^\2\2\u01bc")
        buf.write(u"\u01bd\7e\2\2\u01bd\u01be\7q\2\2\u01be\u01bf\7u\2\2\u01bf")
        buf.write(u"L\3\2\2\2\u01c0\u01c1\7^\2\2\u01c1\u01c2\7v\2\2\u01c2")
        buf.write(u"\u01c3\7c\2\2\u01c3\u01c4\7p\2\2\u01c4N\3\2\2\2\u01c5")
        buf.write(u"\u01c6\7^\2\2\u01c6\u01c7\7e\2\2\u01c7\u01c8\7u\2\2\u01c8")
        buf.write(u"\u01c9\7e\2\2\u01c9P\3\2\2\2\u01ca\u01cb\7^\2\2\u01cb")
        buf.write(u"\u01cc\7u\2\2\u01cc\u01cd\7g\2\2\u01cd\u01ce\7e\2\2\u01ce")
        buf.write(u"R\3\2\2\2\u01cf\u01d0\7^\2\2\u01d0\u01d1\7e\2\2\u01d1")
        buf.write(u"\u01d2\7q\2\2\u01d2\u01d3\7v\2\2\u01d3T\3\2\2\2\u01d4")
        buf.write(u"\u01d5\7^\2\2\u01d5\u01d6\7c\2\2\u01d6\u01d7\7t\2\2\u01d7")
        buf.write(u"\u01d8\7e\2\2\u01d8\u01d9\7u\2\2\u01d9\u01da\7k\2\2\u01da")
        buf.write(u"\u01db\7p\2\2\u01dbV\3\2\2\2\u01dc\u01dd\7^\2\2\u01dd")
        buf.write(u"\u01de\7c\2\2\u01de\u01df\7t\2\2\u01df\u01e0\7e\2\2\u01e0")
        buf.write(u"\u01e1\7e\2\2\u01e1\u01e2\7q\2\2\u01e2\u01e3\7u\2\2\u01e3")
        buf.write(u"X\3\2\2\2\u01e4\u01e5\7^\2\2\u01e5\u01e6\7c\2\2\u01e6")
        buf.write(u"\u01e7\7t\2\2\u01e7\u01e8\7e\2\2\u01e8\u01e9\7v\2\2\u01e9")
        buf.write(u"\u01ea\7c\2\2\u01ea\u01eb\7p\2\2\u01ebZ\3\2\2\2\u01ec")
        buf.write(u"\u01ed\7^\2\2\u01ed\u01ee\7c\2\2\u01ee\u01ef\7t\2\2\u01ef")
        buf.write(u"\u01f0\7e\2\2\u01f0\u01f1\7e\2\2\u01f1\u01f2\7u\2\2\u01f2")
        buf.write(u"\u01f3\7e\2\2\u01f3\\\3\2\2\2\u01f4\u01f5\7^\2\2\u01f5")
        buf.write(u"\u01f6\7c\2\2\u01f6\u01f7\7t\2\2\u01f7\u01f8\7e\2\2\u01f8")
        buf.write(u"\u01f9\7u\2\2\u01f9\u01fa\7g\2\2\u01fa\u01fb\7e\2\2\u01fb")
        buf.write(u"^\3\2\2\2\u01fc\u01fd\7^\2\2\u01fd\u01fe\7c\2\2\u01fe")
        buf.write(u"\u01ff\7t\2\2\u01ff\u0200\7e\2\2\u0200\u0201\7e\2\2\u0201")
        buf.write(u"\u0202\7q\2\2\u0202\u0203\7v\2\2\u0203`\3\2\2\2\u0204")
        buf.write(u"\u0205\7^\2\2\u0205\u0206\7u\2\2\u0206\u0207\7k\2\2\u0207")
        buf.write(u"\u0208\7p\2\2\u0208\u0209\7j\2\2\u0209b\3\2\2\2\u020a")
        buf.write(u"\u020b\7^\2\2\u020b\u020c\7e\2\2\u020c\u020d\7q\2\2\u020d")
        buf.write(u"\u020e\7u\2\2\u020e\u020f\7j\2\2\u020fd\3\2\2\2\u0210")
        buf.write(u"\u0211\7^\2\2\u0211\u0212\7v\2\2\u0212\u0213\7c\2\2\u0213")
        buf.write(u"\u0214\7p\2\2\u0214\u0215\7j\2\2\u0215f\3\2\2\2\u0216")
        buf.write(u"\u0217\7^\2\2\u0217\u0218\7c\2\2\u0218\u0219\7t\2\2\u0219")
        buf.write(u"\u021a\7u\2\2\u021a\u021b\7k\2\2\u021b\u021c\7p\2\2\u021c")
        buf.write(u"\u021d\7j\2\2\u021dh\3\2\2\2\u021e\u021f\7^\2\2\u021f")
        buf.write(u"\u0220\7c\2\2\u0220\u0221\7t\2\2\u0221\u0222\7e\2\2\u0222")
        buf.write(u"\u0223\7q\2\2\u0223\u0224\7u\2\2\u0224\u0225\7j\2\2\u0225")
        buf.write(u"j\3\2\2\2\u0226\u0227\7^\2\2\u0227\u0228\7c\2\2\u0228")
        buf.write(u"\u0229\7t\2\2\u0229\u022a\7v\2\2\u022a\u022b\7c\2\2\u022b")
        buf.write(u"\u022c\7p\2\2\u022c\u022d\7j\2\2\u022dl\3\2\2\2\u022e")
        buf.write(u"\u022f\7^\2\2\u022f\u0230\7u\2\2\u0230\u0231\7s\2\2\u0231")
        buf.write(u"\u0232\7t\2\2\u0232\u0233\7v\2\2\u0233n\3\2\2\2\u0234")
        buf.write(u"\u0235\7^\2\2\u0235\u0236\7v\2\2\u0236\u0237\7k\2\2\u0237")
        buf.write(u"\u0238\7o\2\2\u0238\u0239\7g\2\2\u0239\u023a\7u\2\2\u023a")
        buf.write(u"p\3\2\2\2\u023b\u023c\7^\2\2\u023c\u023d\7e\2\2\u023d")
        buf.write(u"\u023e\7f\2\2\u023e\u023f\7q\2\2\u023f\u0240\7v\2\2\u0240")
        buf.write(u"r\3\2\2\2\u0241\u0242\7^\2\2\u0242\u0243\7f\2\2\u0243")
        buf.write(u"\u0244\7k\2\2\u0244\u0245\7x\2\2\u0245t\3\2\2\2\u0246")
        buf.write(u"\u0247\7^\2\2\u0247\u0248\7h\2\2\u0248\u0249\7t\2\2\u0249")
        buf.write(u"\u024a\7c\2\2\u024a\u024b\7e\2\2\u024bv\3\2\2\2\u024c")
        buf.write(u"\u024d\7^\2\2\u024d\u024e\7d\2\2\u024e\u024f\7k\2\2\u024f")
        buf.write(u"\u0250\7p\2\2\u0250\u0251\7q\2\2\u0251\u0252\7o\2\2\u0252")
        buf.write(u"x\3\2\2\2\u0253\u0254\7^\2\2\u0254\u0255\7f\2\2\u0255")
        buf.write(u"\u0256\7d\2\2\u0256\u0257\7k\2\2\u0257\u0258\7p\2\2\u0258")
        buf.write(u"\u0259\7q\2\2\u0259\u025a\7o\2\2\u025az\3\2\2\2\u025b")
        buf.write(u"\u025c\7^\2\2\u025c\u025d\7v\2\2\u025d\u025e\7d\2\2\u025e")
        buf.write(u"\u025f\7k\2\2\u025f\u0260\7p\2\2\u0260\u0261\7q\2\2\u0261")
        buf.write(u"\u0262\7o\2\2\u0262|\3\2\2\2\u0263\u0264\7^\2\2\u0264")
        buf.write(u"\u0265\7o\2\2\u0265\u0266\7c\2\2\u0266\u0267\7v\2\2\u0267")
        buf.write(u"\u0268\7j\2\2\u0268\u0269\7k\2\2\u0269\u026a\7v\2\2\u026a")
        buf.write(u"~\3\2\2\2\u026b\u026c\7a\2\2\u026c\u0080\3\2\2\2\u026d")
        buf.write(u"\u026e\7`\2\2\u026e\u0082\3\2\2\2\u026f\u0270\7<\2\2")
        buf.write(u"\u0270\u0084\3\2\2\2\u0271\u0272\t\2\2\2\u0272\u0086")
        buf.write(u"\3\2\2\2\u0273\u0277\7f\2\2\u0274\u0276\5\u0085C\2\u0275")
        buf.write(u"\u0274\3\2\2\2\u0276\u0279\3\2\2\2\u0277\u0278\3\2\2")
        buf.write(u"\2\u0277\u0275\3\2\2\2\u0278\u0281\3\2\2\2\u0279\u0277")
        buf.write(u"\3\2\2\2\u027a\u0282\t\3\2\2\u027b\u027d\7^\2\2\u027c")
        buf.write(u"\u027e\t\3\2\2\u027d\u027c\3\2\2\2\u027e\u027f\3\2\2")
        buf.write(u"\2\u027f\u027d\3\2\2\2\u027f\u0280\3\2\2\2\u0280\u0282")
        buf.write(u"\3\2\2\2\u0281\u027a\3\2\2\2\u0281\u027b\3\2\2\2\u0282")
        buf.write(u"\u0088\3\2\2\2\u0283\u0284\t\3\2\2\u0284\u008a\3\2\2")
        buf.write(u"\2\u0285\u0286\t\4\2\2\u0286\u008c\3\2\2\2\u0287\u0289")
        buf.write(u"\5\u008bF\2\u0288\u0287\3\2\2\2\u0289\u028a\3\2\2\2\u028a")
        buf.write(u"\u0288\3\2\2\2\u028a\u028b\3\2\2\2\u028b\u0293\3\2\2")
        buf.write(u"\2\u028c\u028d\7.\2\2\u028d\u028e\5\u008bF\2\u028e\u028f")
        buf.write(u"\5\u008bF\2\u028f\u0290\5\u008bF\2\u0290\u0292\3\2\2")
        buf.write(u"\2\u0291\u028c\3\2\2\2\u0292\u0295\3\2\2\2\u0293\u0291")
        buf.write(u"\3\2\2\2\u0293\u0294\3\2\2\2\u0294\u02ad\3\2\2\2\u0295")
        buf.write(u"\u0293\3\2\2\2\u0296\u0298\5\u008bF\2\u0297\u0296\3\2")
        buf.write(u"\2\2\u0298\u029b\3\2\2\2\u0299\u0297\3\2\2\2\u0299\u029a")
        buf.write(u"\3\2\2\2\u029a\u02a3\3\2\2\2\u029b\u0299\3\2\2\2\u029c")
        buf.write(u"\u029d\7.\2\2\u029d\u029e\5\u008bF\2\u029e\u029f\5\u008b")
        buf.write(u"F\2\u029f\u02a0\5\u008bF\2\u02a0\u02a2\3\2\2\2\u02a1")
        buf.write(u"\u029c\3\2\2\2\u02a2\u02a5\3\2\2\2\u02a3\u02a1\3\2\2")
        buf.write(u"\2\u02a3\u02a4\3\2\2\2\u02a4\u02a6\3\2\2\2\u02a5\u02a3")
        buf.write(u"\3\2\2\2\u02a6\u02a8\7\60\2\2\u02a7\u02a9\5\u008bF\2")
        buf.write(u"\u02a8\u02a7\3\2\2\2\u02a9\u02aa\3\2\2\2\u02aa\u02a8")
        buf.write(u"\3\2\2\2\u02aa\u02ab\3\2\2\2\u02ab\u02ad\3\2\2\2\u02ac")
        buf.write(u"\u0288\3\2\2\2\u02ac\u0299\3\2\2\2\u02ad\u008e\3\2\2")
        buf.write(u"\2\u02ae\u02af\7?\2\2\u02af\u0090\3\2\2\2\u02b0\u02b1")
        buf.write(u"\7>\2\2\u02b1\u0092\3\2\2\2\u02b2\u02b3\7^\2\2\u02b3")
        buf.write(u"\u02b4\7n\2\2\u02b4\u02b5\7g\2\2\u02b5\u02b6\7s\2\2\u02b6")
        buf.write(u"\u0094\3\2\2\2\u02b7\u02b8\7@\2\2\u02b8\u0096\3\2\2\2")
        buf.write(u"\u02b9\u02ba\7^\2\2\u02ba\u02bb\7i\2\2\u02bb\u02bc\7")
        buf.write(u"g\2\2\u02bc\u02bd\7s\2\2\u02bd\u0098\3\2\2\2\u02be\u02bf")
        buf.write(u"\7#\2\2\u02bf\u009a\3\2\2\2\u02c0\u02c2\7^\2\2\u02c1")
        buf.write(u"\u02c3\t\3\2\2\u02c2\u02c1\3\2\2\2\u02c3\u02c4\3\2\2")
        buf.write(u"\2\u02c4\u02c2\3\2\2\2\u02c4\u02c5\3\2\2\2\u02c5\u009c")
        buf.write(u"\3\2\2\2\23\2\u00a2\u00b2\u00c1\u00d2\u00f6\u0196\u0277")
        buf.write(u"\u027f\u0281\u028a\u0293\u0299\u02a3\u02aa\u02ac\u02c4")
        buf.write(u"\3\b\2\2")
        return buf.getvalue()


class LaTeXLexer(Lexer):

    atn = ATNDeserializer().deserialize(serializedATN())

    decisionsToDFA = [ DFA(ds, i) for i, ds in enumerate(atn.decisionToState) ]

    T__0 = 1
    WS = 2
    THINSPACE = 3
    MEDSPACE = 4
    THICKSPACE = 5
    QUAD = 6
    QQUAD = 7
    NEGTHINSPACE = 8
    NEGMEDSPACE = 9
    NEGTHICKSPACE = 10
    ADD = 11
    SUB = 12
    MUL = 13
    DIV = 14
    L_PAREN = 15
    R_PAREN = 16
    L_BRACE = 17
    R_BRACE = 18
    L_BRACE_LITERAL = 19
    R_BRACE_LITERAL = 20
    L_BRACKET = 21
    R_BRACKET = 22
    CMD_LEFT = 23
    CMD_RIGHT = 24
    CMD_MLEFT = 25
    CMD_MRIGHT = 26
    BAR = 27
    FUNC_LIM = 28
    LIM_APPROACH_SYM = 29
    FUNC_INT = 30
    FUNC_SUM = 31
    FUNC_PROD = 32
    FUNC_EXP = 33
    FUNC_LOG = 34
    FUNC_LN = 35
    FUNC_SIN = 36
    FUNC_COS = 37
    FUNC_TAN = 38
    FUNC_CSC = 39
    FUNC_SEC = 40
    FUNC_COT = 41
    FUNC_ARCSIN = 42
    FUNC_ARCCOS = 43
    FUNC_ARCTAN = 44
    FUNC_ARCCSC = 45
    FUNC_ARCSEC = 46
    FUNC_ARCCOT = 47
    FUNC_SINH = 48
    FUNC_COSH = 49
    FUNC_TANH = 50
    FUNC_ARSINH = 51
    FUNC_ARCOSH = 52
    FUNC_ARTANH = 53
    FUNC_SQRT = 54
    CMD_TIMES = 55
    CMD_CDOT = 56
    CMD_DIV = 57
    CMD_FRAC = 58
    CMD_BINOM = 59
    CMD_DBINOM = 60
    CMD_TBINOM = 61
    CMD_MATHIT = 62
    UNDERSCORE = 63
    CARET = 64
    COLON = 65
    DIFFERENTIAL = 66
    LETTER = 67
    NUMBER = 68
    EQUAL = 69
    LT = 70
    LTE = 71
    GT = 72
    GTE = 73
    BANG = 74
    SYMBOL = 75

    channelNames = [ u"DEFAULT_TOKEN_CHANNEL", u"HIDDEN" ]

    modeNames = [ u"DEFAULT_MODE" ]

    literalNames = [ u"<INVALID>",
            u"','", u"'\\quad'", u"'\\qquad'", u"'\\negmedspace'", u"'\\negthickspace'",
            u"'+'", u"'-'", u"'*'", u"'/'", u"'('", u"')'", u"'{'", u"'}'",
            u"'\\{'", u"'\\}'", u"'['", u"']'", u"'\\left'", u"'\\right'",
            u"'\\mleft'", u"'\\mright'", u"'|'", u"'\\lim'", u"'\\int'",
            u"'\\sum'", u"'\\prod'", u"'\\exp'", u"'\\log'", u"'\\ln'",
            u"'\\sin'", u"'\\cos'", u"'\\tan'", u"'\\csc'", u"'\\sec'",
            u"'\\cot'", u"'\\arcsin'", u"'\\arccos'", u"'\\arctan'", u"'\\arccsc'",
            u"'\\arcsec'", u"'\\arccot'", u"'\\sinh'", u"'\\cosh'", u"'\\tanh'",
            u"'\\arsinh'", u"'\\arcosh'", u"'\\artanh'", u"'\\sqrt'", u"'\\times'",
            u"'\\cdot'", u"'\\div'", u"'\\frac'", u"'\\binom'", u"'\\dbinom'",
            u"'\\tbinom'", u"'\\mathit'", u"'_'", u"'^'", u"':'", u"'='",
            u"'<'", u"'\\leq'", u"'>'", u"'\\geq'", u"'!'" ]

    symbolicNames = [ u"<INVALID>",
            u"WS", u"THINSPACE", u"MEDSPACE", u"THICKSPACE", u"QUAD", u"QQUAD",
            u"NEGTHINSPACE", u"NEGMEDSPACE", u"NEGTHICKSPACE", u"ADD", u"SUB",
            u"MUL", u"DIV", u"L_PAREN", u"R_PAREN", u"L_BRACE", u"R_BRACE",
            u"L_BRACE_LITERAL", u"R_BRACE_LITERAL", u"L_BRACKET", u"R_BRACKET",
            u"CMD_LEFT", u"CMD_RIGHT", u"CMD_MLEFT", u"CMD_MRIGHT", u"BAR",
            u"FUNC_LIM", u"LIM_APPROACH_SYM", u"FUNC_INT", u"FUNC_SUM",
            u"FUNC_PROD", u"FUNC_EXP", u"FUNC_LOG", u"FUNC_LN", u"FUNC_SIN",
            u"FUNC_COS", u"FUNC_TAN", u"FUNC_CSC", u"FUNC_SEC", u"FUNC_COT",
            u"FUNC_ARCSIN", u"FUNC_ARCCOS", u"FUNC_ARCTAN", u"FUNC_ARCCSC",
            u"FUNC_ARCSEC", u"FUNC_ARCCOT", u"FUNC_SINH", u"FUNC_COSH",
            u"FUNC_TANH", u"FUNC_ARSINH", u"FUNC_ARCOSH", u"FUNC_ARTANH",
            u"FUNC_SQRT", u"CMD_TIMES", u"CMD_CDOT", u"CMD_DIV", u"CMD_FRAC",
            u"CMD_BINOM", u"CMD_DBINOM", u"CMD_TBINOM", u"CMD_MATHIT", u"UNDERSCORE",
            u"CARET", u"COLON", u"DIFFERENTIAL", u"LETTER", u"NUMBER", u"EQUAL",
            u"LT", u"LTE", u"GT", u"GTE", u"BANG", u"SYMBOL" ]

    ruleNames = [ u"T__0", u"WS", u"THINSPACE", u"MEDSPACE", u"THICKSPACE",
                  u"QUAD", u"QQUAD", u"NEGTHINSPACE", u"NEGMEDSPACE", u"NEGTHICKSPACE",
                  u"ADD", u"SUB", u"MUL", u"DIV", u"L_PAREN", u"R_PAREN",
                  u"L_BRACE", u"R_BRACE", u"L_BRACE_LITERAL", u"R_BRACE_LITERAL",
                  u"L_BRACKET", u"R_BRACKET", u"CMD_LEFT", u"CMD_RIGHT",
                  u"CMD_MLEFT", u"CMD_MRIGHT", u"BAR", u"FUNC_LIM", u"LIM_APPROACH_SYM",
                  u"FUNC_INT", u"FUNC_SUM", u"FUNC_PROD", u"FUNC_EXP", u"FUNC_LOG",
                  u"FUNC_LN", u"FUNC_SIN", u"FUNC_COS", u"FUNC_TAN", u"FUNC_CSC",
                  u"FUNC_SEC", u"FUNC_COT", u"FUNC_ARCSIN", u"FUNC_ARCCOS",
                  u"FUNC_ARCTAN", u"FUNC_ARCCSC", u"FUNC_ARCSEC", u"FUNC_ARCCOT",
                  u"FUNC_SINH", u"FUNC_COSH", u"FUNC_TANH", u"FUNC_ARSINH",
                  u"FUNC_ARCOSH", u"FUNC_ARTANH", u"FUNC_SQRT", u"CMD_TIMES",
                  u"CMD_CDOT", u"CMD_DIV", u"CMD_FRAC", u"CMD_BINOM", u"CMD_DBINOM",
                  u"CMD_TBINOM", u"CMD_MATHIT", u"UNDERSCORE", u"CARET",
                  u"COLON", u"WS_CHAR", u"DIFFERENTIAL", u"LETTER", u"DIGIT",
                  u"NUMBER", u"EQUAL", u"LT", u"LTE", u"GT", u"GTE", u"BANG",
                  u"SYMBOL" ]

    grammarFileName = u"LaTeX.g4"

    def __init__(self, input=None, output=sys.stdout):
        super(LaTeXLexer, self).__init__(input, output=output)
        self.checkVersion("4.8")
        self._interp = LexerATNSimulator(self, self.atn, self.decisionsToDFA, PredictionContextCache())
        self._actions = None
        self._predicates = None


